# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Computational Methods in Physics'
tagline:             'ASU Physics PHY 494'
description:         > 
                     A <a
                     href="http://becksteinlab.physics.asu.edu/learning/76/phy494-computational-physics">class
                     at Arizona State University</a> that teaches
                     students how to use the computer as a tool to
                     solve problems in physics
url:                 http://asu-compmethodsphysics-phy494.github.io
baseurl:             /ASU-PHY494
paginate:            5

# About/contact
author:
  name:              'Oliver Beckstein'
  url:               http://becksteinlab.physics.asu.edu
  email:             oliver.beckstein@asu.edu

# Custom vars
version:             'Fall 2016'

course:
 url:                http://becksteinlab.physics.asu.edu/learning/76/phy494-computational-physics


#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
swc_blog        : "http://software-carpentry.org/feed.xml"
swc_contact     : "admin@software-carpentry.org"
swc_files       : "http://files.software-carpentry.org"
swc_github      : "http://github.com/swcarpentry"
swc_githubio    : "http://swcarpentry.github.io/"
swc_installer   : "http://files.software-carpentry.org/SWCarpentryInstaller.exe"
swc_site        : "http://software-carpentry.org"
swc_twitter     : "http://twitter.com/swcarpentry"
swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtSTZLQzF4aVB4NDQ&export=download"
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
