# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Since Feb 1 and Jekyll 3.0, relative_permalinks do not work anymore
# https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
### relative_permalinks: true

# Setup
title:               'Computational Methods in Physics'
tagline:             'ASU Physics PHY 494'
description:         > 
                     A <a
                     href="http://becksteinlab.physics.asu.edu/learning/76/phy494-computational-physics">class
                     at Arizona State University</a> that teaches
                     students how to use the computer as a tool to
                     solve problems in physics
url:                 http://asu-compmethodsphysics-phy494.github.io
baseurl:             /ASU-PHY494
paginate:            1

# About/contact
author:
  name:              'Oliver Beckstein'
  url:               http://becksteinlab.physics.asu.edu/people/11/oliver-beckstein
  email:             oliver.beckstein@asu.edu

# Custom vars
version:             'Fall 2016'


# use as {{site.baseurl}}/{{site.data}}
data:                "public/data"
figs:                "public/figs"
lectures:            "public/lectures"

course:
 url:                http://becksteinlab.physics.asu.edu/learning/76/phy494-computational-physics

resources:
 name:               ASU-CompMethodsPhysics-PHY494/PHY494-resources
 shortname:          PHY494-resources
 url:                https://github.com/ASU-CompMethodsPhysics-PHY494/PHY494-resources


#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - only included what is be needed
#--------------------------------------------------------------------------------
swc_installer   : "http://files.software-carpentry.org/SWCarpentryInstaller.exe"
swc_site        : "http://software-carpentry.org"

#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
