# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               'Computational Methods in Physics'
tagline:             'ASU Physics PHY 494'
description:         > 
                     A <a
                     href="http://becksteinlab.physics.asu.edu/learning/76/phy494-computational-physics">class
                     at Arizona State University</a> that teaches
                     students how to use the computer as a tool to
                     solve problems in physics
url:                 http://asu-compmethodsphysics-phy494.github.io
baseurl:             /ASU-PHY494
paginate:            1

# About/contact
author:
  name:              'Oliver Beckstein'
  url:               http://becksteinlab.physics.asu.edu/people/11/oliver-beckstein
  email:             oliver.beckstein@asu.edu

# Custom vars
version:             'Fall 2016'

# see https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed

# use as {{site.baseurl}}/{{site.data}}
data:                "public/data"
figs:                "public/figs"
lectures:            "public/lectures"
docs:                "public/docs"

course:
 url:                http://becksteinlab.physics.asu.edu/learning/76/phy494-computational-physics

resources:
 name:               ASU-CompMethodsPhysics-PHY494/PHY494-resources
 shortname:          PHY494-resources
 url:                https://github.com/ASU-CompMethodsPhysics-PHY494/PHY494-resources
 fileurl:            https://github.com/ASU-CompMethodsPhysics-PHY494/PHY494-resources/blob/master


org:
 name:               ASU-CompMethodsPhysics-PHY494
 shortname:          GitHub site
 url:                https://github.com/ASU-CompMethodsPhysics-PHY494/

nbviewer:
   show:             http://nbviewer.jupyter.org/github
   resources:        http://nbviewer.jupyter.org/github/ASU-CompMethodsPhysics-PHY494/PHY494-resources/blob/master

#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - only included what is be needed
#--------------------------------------------------------------------------------
swc_installer   : "http://files.software-carpentry.org/SWCarpentryInstaller.exe"
swc_site        : "http://software-carpentry.org"

#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
